export { default as Loader } from "./loader/loader.component"
export { default as Header } from "./header/header.component"
export { default as Text } from "./text/text.component"
export { default as Box } from "./box/box.component"
export { default as Button } from "./button/button.component"
export { default as Input } from "./input/input.component"
export { default as Textarea } from "./textarea/textarea.component"
export { default as Pagination } from "./pagination/pagination.component"
